# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xincidian.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        Form.setMinimumSize(QtCore.QSize(700, 500))
        Form.setMaximumSize(QtCore.QSize(700, 500))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 201, 51))
        self.widget.setMinimumSize(QtCore.QSize(201, 51))
        self.widget.setStyleSheet("image: url(:/图片素材/wmcd.png);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(0, 50, 201, 451))
        self.widget_2.setMinimumSize(QtCore.QSize(201, 451))
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 101, 31))
        self.label_3.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("image: url(:/图片素材/dccx.png);\n"
"color: rgb(0, 170, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(40, 60, 101, 31))
        self.label_4.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("image: url(:/图片素材/dcb1.png);\n"
"color: rgb(0, 170, 255);")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(40, 100, 101, 31))
        self.label.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("image: url(:/图片素材/jpk1.png);\n"
"color: rgb(0, 170, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 101, 31))
        self.label_2.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("image: url(:/图片素材/rgfy1.png);\n"
"color: rgb(0, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setGeometry(QtCore.QRect(60, 270, 81, 20))
        self.checkBox.setMinimumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_2.setGeometry(QtCore.QRect(60, 290, 81, 20))
        self.checkBox_2.setMinimumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: rgb(0, 170, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gd1 = QtWidgets.QWidget(self.widget_2)
        self.gd1.setGeometry(QtCore.QRect(10, 170, 191, 101))
        self.gd1.setStyleSheet("image: url(:/图片素材/cxc.jpg);")
        self.gd1.setObjectName("gd1")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 320, 181, 101))
        self.widget_3.setStyleSheet("image: url(:/图片素材/gtl.jpg);")
        self.widget_3.setObjectName("widget_3")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(210, 50, 481, 201))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(660, 10, 31, 31))
        self.toolButton.setMinimumSize(QtCore.QSize(31, 31))
        self.toolButton.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Form)
        self.toolButton_2.setGeometry(QtCore.QRect(630, 10, 31, 31))
        self.toolButton_2.setMinimumSize(QtCore.QSize(31, 31))
        self.toolButton_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.toolButton_2.setText("")
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(Form)
        self.toolButton_3.setGeometry(QtCore.QRect(600, 10, 31, 31))
        self.toolButton_3.setMinimumSize(QtCore.QSize(31, 31))
        self.toolButton_3.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.toolButton_3.setText("")
        self.toolButton_3.setObjectName("toolButton_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(220, 450, 101, 31))
        self.label_5.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("image: url(:/图片素材/wdcx.png);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(340, 450, 101, 31))
        self.label_6.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("image: url(:/图片素材/jt.png);")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(580, 450, 100, 30))
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(210, 270, 481, 221))
        self.textEdit_2.setStyleSheet("")
        self.textEdit_2.setObjectName("textEdit_2")
        self.toolButton_4 = QtWidgets.QToolButton(Form)
        self.toolButton_4.setGeometry(QtCore.QRect(510, 450, 31, 31))
        self.toolButton_4.setMinimumSize(QtCore.QSize(31, 31))
        self.toolButton_4.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.toolButton_4.setText("")
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(Form)
        self.toolButton_5.setGeometry(QtCore.QRect(540, 450, 31, 31))
        self.toolButton_5.setMinimumSize(QtCore.QSize(31, 31))
        self.toolButton_5.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.toolButton_5.setText("")
        self.toolButton_5.setObjectName("toolButton_5")
        self.textEdit_2.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.widget.raise_()
        self.widget_2.raise_()
        self.textEdit.raise_()
        self.toolButton.raise_()
        self.toolButton_2.raise_()
        self.toolButton_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.pushButton.raise_()
        self.toolButton_4.raise_()
        self.toolButton_5.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "        查词翻译"))
        self.label_4.setText(_translate("Form", "          单词本"))
        self.label.setText(_translate("Form", "          精品课"))
        self.label_2.setText(_translate("Form", "        人工翻译"))
        self.checkBox.setText(_translate("Form", "  取  词"))
        self.checkBox_2.setText(_translate("Form", "  划  词"))
        self.label_5.setText(_translate("Form", "         文档翻译"))
        self.label_6.setText(_translate("Form", "         截屏翻译"))
        self.pushButton.setText(_translate("Form", "翻 译"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)   
    myapp = WanMaDicot()   #MyForm是自己的窗体类名
    myapp.show()   
    sys.exit(app.exec_())
# import tp_rc
